### PR TITLE
add coo_matrix option returned by one-hot-encoder and test

### PR DESCRIPTION
**Pull request by tianxin1860**
This pull request is for dealling with categorical features having large number of levels in it, for example, "user_id" or "item_id"。

### CODE REVIEW

**Comment by yashu-seth** [comment]
@tianxin1860 Looks fine to me. Can you please add tests for the changes too?

**Comment by tianxin1860** [comment]
Maybe after you fix [the bug](https://github.com/yashu-seth/dummyPy/issues/4) I can add tests for this change easily.

**Comment by tianxin1860** [comment]
@yashu-seth Maybe after you fix [the bug](https://github.com/yashu-seth/dummyPy/issues/4) I can add tests for this change easily.

**Comment by yashu-seth** [comment]
@tianxin1860 The bug is mostly unrelated to this. But, sure I will look into that soon.

**Comment by tianxin1860** [comment]
@yashu-seth Hi, I have added tests for OneHotEncoder return coo_matrix.

**Comment by yashu-seth** [comment]
@tianxin1860 Thanks for the PR.

**Pull request merged**
